### PR TITLE
add material based theme

### PR DESCRIPTION
**Pull request by Nexucis**
image

image

/cc @juliusv

### CODE REVIEW

**Comment by Nexucis** [comment]
well it looks like Circle-ci has some issues with npm. I will have to re-run the build a bit later: 
image

**Comment by slrtbtfs** [comment]
Looking at the screenshot, the green on white looks barely readable to me. Could this be replaced by a darker tone?

**Comment by Nexucis** [comment]
better ? 
image

**Comment by slrtbtfs** [comment]
Yes.

**Comment by Nexucis** [comment]
related to #5

**Comment by juliusv** [comment]
Btw., this was my theme to make it look like Monaco / promlens.com:

```typescript
{
      name: { color: '#000' },
      number: { color: '#09885a' },
      string: { color: '#a31515' },
      keyword: { color: '#008080' },
      labelName: { color: '#800000' },
      operator: {},
      modifier: { color: '#008080' },
      paren: {},
      squareBracket: {},
      brace: {},
      invalid: { color: 'red' },
      comment: { color: '#888', fontStyle: 'italic' },
    }
```

...though that was a while ago, could be that would need an update after the latest CM-promql changes.

**Comment by Nexucis** [comment]
Well it won't hurt to add another one :). Like `promQLHighlightMonacoTheme`.

I'm not really certain theme should be delivered by this lib actually. But well for the moment it won't be a big issue to add it here

**Comment by juliusv** [comment]
I just commented since it might be interesting. Yeah, I don't think themes should go into this repo, or that they should even be tied to a language at all.

**Comment by Nexucis** [comment]
yeah I'm agree, theme should be delivered by CMN directly. Like it is for the previous version.

Since it's not yet available and since I would like to have some nice color for the playground I added this theme. So that mean, if you want we can add as well yours :)

**Comment by juliusv** [comment]
If you want a nice theme for the playground, I would propose just putting that theme code directly into the playground example code, rather than into the `lang-promql` subdir?

**Comment by Nexucis** [comment]
mmm yeah makes sense, I will change that. Thanks for the suggestion :)

**Comment by Nexucis** [comment]
regarding the theme you posted, yeah it requires some adjustment if we want to use it in Prometheus/ PromLabs, but nothing too serious.

**Pull request merged**
