### PR TITLE
Synchronize codemirror from prometheus/prometheus

### PR DESCRIPTION
**Pull request by prombot**
Propagating changes from prometheus/prometheus default branch.

### CODE REVIEW

**Comment by Nexucis** [comment]
@roidelapluie it's almost good ! Just it shouldn't remove the circleci config, the licence and other .md files.
Perhaps an easy way for the circleci config is just to add it back in prometheus.
But perhaps you prefer a smarter way ?

**Comment by Nexucis** [comment]
@juliusv: can you remove the netifly config. The app package doesn't existe anymore so netifly is in error

**Comment by juliusv** [comment]
Deleted it! I think we just have to ignore the Netlify checks on this PR here then.

**Comment by roidelapluie** [comment]
> @roidelapluie it's almost good ! Just it shouldn't remove the circleci config, the licence and other .md files.
> Perhaps an easy way for the circleci config is just to add it back in prometheus.
> But perhaps you prefer a smarter way ?

There is a smarter way. But I think we need to change the script. It is using git restore. Maybe the git version does not support it and we have to get back to git checkout.

**Comment by roidelapluie** [comment]
git: 'restore' is not a git command. See 'git --help'.

**Comment by Nexucis** [comment]
mmm probably we could just upgrade git don't you think @roidelapluie ?

**Comment by roidelapluie** [comment]
https://github.com/prometheus/golang-builder/pull/120 not-as-easy-as-it-looks

**Comment by Nexucis** [comment]
I will take a look at this PR then

**Pull request closed without merging**
